version: 2
updates:
  # Updates workflows & composite actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
