version: 2
updates:
  # Updates workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Composite actions need to be updated separately
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/setup"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
