import Foundation
import NSAttributedStringBuilder
import Testing

@Suite
struct LanguageCodeTests {

    @Test
    func initWithRawValue() {
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ain") == AttributedStringBuilder.LanguageCode.ainu)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "sq") == AttributedStringBuilder.LanguageCode.albanian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "am") == AttributedStringBuilder.LanguageCode.amharic)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "apw") == AttributedStringBuilder.LanguageCode.apacheWestern)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ar") == AttributedStringBuilder.LanguageCode.arabic)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "hy") == AttributedStringBuilder.LanguageCode.armenian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "as") == AttributedStringBuilder.LanguageCode.assamese)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "syr") == AttributedStringBuilder.LanguageCode.assyrian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "az") == AttributedStringBuilder.LanguageCode.azerbaijani)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "bn") == AttributedStringBuilder.LanguageCode.bangla)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "be") == AttributedStringBuilder.LanguageCode.belarusian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "brx") == AttributedStringBuilder.LanguageCode.bodo)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "bg") == AttributedStringBuilder.LanguageCode.bulgarian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "my") == AttributedStringBuilder.LanguageCode.burmese)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "yue") == AttributedStringBuilder.LanguageCode.cantonese)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ca") == AttributedStringBuilder.LanguageCode.catalan)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "chr") == AttributedStringBuilder.LanguageCode.cherokee)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "zh") == AttributedStringBuilder.LanguageCode.chinese)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "hr") == AttributedStringBuilder.LanguageCode.croatian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "cs") == AttributedStringBuilder.LanguageCode.czech)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "da") == AttributedStringBuilder.LanguageCode.danish)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "dv") == AttributedStringBuilder.LanguageCode.dhivehi)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "doi") == AttributedStringBuilder.LanguageCode.dogri)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "nl") == AttributedStringBuilder.LanguageCode.dutch)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "dz") == AttributedStringBuilder.LanguageCode.dzongkha)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "en") == AttributedStringBuilder.LanguageCode.english)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "et") == AttributedStringBuilder.LanguageCode.estonian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "fo") == AttributedStringBuilder.LanguageCode.faroese)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "fi") == AttributedStringBuilder.LanguageCode.finnish)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "fr") == AttributedStringBuilder.LanguageCode.french)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ff") == AttributedStringBuilder.LanguageCode.fula)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ka") == AttributedStringBuilder.LanguageCode.georgian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "de") == AttributedStringBuilder.LanguageCode.german)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "el") == AttributedStringBuilder.LanguageCode.greek)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "gu") == AttributedStringBuilder.LanguageCode.gujarati)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "haw") == AttributedStringBuilder.LanguageCode.hawaiian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "he") == AttributedStringBuilder.LanguageCode.hebrew)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "hi") == AttributedStringBuilder.LanguageCode.hindi)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "hu") == AttributedStringBuilder.LanguageCode.hungarian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "is") == AttributedStringBuilder.LanguageCode.icelandic)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ig") == AttributedStringBuilder.LanguageCode.igbo)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "id") == AttributedStringBuilder.LanguageCode.indonesian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ga") == AttributedStringBuilder.LanguageCode.irish)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "it") == AttributedStringBuilder.LanguageCode.italian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ja") == AttributedStringBuilder.LanguageCode.japanese)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "kn") == AttributedStringBuilder.LanguageCode.kannada)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ks") == AttributedStringBuilder.LanguageCode.kashmiri)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "kk") == AttributedStringBuilder.LanguageCode.kazakh)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "km") == AttributedStringBuilder.LanguageCode.khmer)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "kok") == AttributedStringBuilder.LanguageCode.konkani)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ko") == AttributedStringBuilder.LanguageCode.korean)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ku") == AttributedStringBuilder.LanguageCode.kurdish)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ckb") == AttributedStringBuilder.LanguageCode.kurdishSorani)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ky") == AttributedStringBuilder.LanguageCode.kyrgyz)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "lo") == AttributedStringBuilder.LanguageCode.lao)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "lv") == AttributedStringBuilder.LanguageCode.latvian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "lt") == AttributedStringBuilder.LanguageCode.lithuanian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "mk") == AttributedStringBuilder.LanguageCode.macedonian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "mai") == AttributedStringBuilder.LanguageCode.maithili)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ms") == AttributedStringBuilder.LanguageCode.malay)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ml") == AttributedStringBuilder.LanguageCode.malayalam)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "mt") == AttributedStringBuilder.LanguageCode.maltese)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "mni") == AttributedStringBuilder.LanguageCode.manipuri)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "mr") == AttributedStringBuilder.LanguageCode.marathi)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "mn") == AttributedStringBuilder.LanguageCode.mongolian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "mi") == AttributedStringBuilder.LanguageCode.māori)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "nv") == AttributedStringBuilder.LanguageCode.navajo)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ne") == AttributedStringBuilder.LanguageCode.nepali)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "no") == AttributedStringBuilder.LanguageCode.norwegian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "nb") == AttributedStringBuilder.LanguageCode.norwegianBokmål)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "nn") == AttributedStringBuilder.LanguageCode.norwegianNynorsk)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "or") == AttributedStringBuilder.LanguageCode.odia)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ps") == AttributedStringBuilder.LanguageCode.pashto)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "fa") == AttributedStringBuilder.LanguageCode.persian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "pl") == AttributedStringBuilder.LanguageCode.polish)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "pt") == AttributedStringBuilder.LanguageCode.portuguese)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "rhg") == AttributedStringBuilder.LanguageCode.rohingya)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ro") == AttributedStringBuilder.LanguageCode.romanian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ru") == AttributedStringBuilder.LanguageCode.russian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "sm") == AttributedStringBuilder.LanguageCode.samoan)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "sa") == AttributedStringBuilder.LanguageCode.sanskrit)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "sat") == AttributedStringBuilder.LanguageCode.santali)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "sr") == AttributedStringBuilder.LanguageCode.serbian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "sd") == AttributedStringBuilder.LanguageCode.sindhi)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "si") == AttributedStringBuilder.LanguageCode.sinhala)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "sk") == AttributedStringBuilder.LanguageCode.slovak)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "sl") == AttributedStringBuilder.LanguageCode.slovenian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "es") == AttributedStringBuilder.LanguageCode.spanish)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "sw") == AttributedStringBuilder.LanguageCode.swahili)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "sv") == AttributedStringBuilder.LanguageCode.swedish)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "tl") == AttributedStringBuilder.LanguageCode.tagalog)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "tg") == AttributedStringBuilder.LanguageCode.tajik)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ta") == AttributedStringBuilder.LanguageCode.tamil)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "te") == AttributedStringBuilder.LanguageCode.telugu)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "th") == AttributedStringBuilder.LanguageCode.thai)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "bo") == AttributedStringBuilder.LanguageCode.tibetan)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "to") == AttributedStringBuilder.LanguageCode.tongan)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "tr") == AttributedStringBuilder.LanguageCode.turkish)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "tk") == AttributedStringBuilder.LanguageCode.turkmen)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "uk") == AttributedStringBuilder.LanguageCode.ukrainian)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ur") == AttributedStringBuilder.LanguageCode.urdu)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "ug") == AttributedStringBuilder.LanguageCode.uyghur)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "uz") == AttributedStringBuilder.LanguageCode.uzbek)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "vi") == AttributedStringBuilder.LanguageCode.vietnamese)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "cy") == AttributedStringBuilder.LanguageCode.welsh)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "yi") == AttributedStringBuilder.LanguageCode.yiddish)

        #expect(AttributedStringBuilder.LanguageCode(rawValue: "mul") == AttributedStringBuilder.LanguageCode.multiple)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "zxx") == AttributedStringBuilder.LanguageCode.unavailable)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "mis") == AttributedStringBuilder.LanguageCode.uncoded)
        #expect(AttributedStringBuilder.LanguageCode(rawValue: "und") == AttributedStringBuilder.LanguageCode.unidentified)

        #expect(AttributedStringBuilder.LanguageCode(rawValue: .unique()) == nil)
    }

    @Test
    func initExpressibleByStringLiteral() {
        #expect("ain" == AttributedStringBuilder.LanguageCode.ainu)
        #expect("sq" == AttributedStringBuilder.LanguageCode.albanian)
        #expect("am" == AttributedStringBuilder.LanguageCode.amharic)
        #expect("apw" == AttributedStringBuilder.LanguageCode.apacheWestern)
        #expect("ar" == AttributedStringBuilder.LanguageCode.arabic)
        #expect("hy" == AttributedStringBuilder.LanguageCode.armenian)
        #expect("as" == AttributedStringBuilder.LanguageCode.assamese)
        #expect("syr" == AttributedStringBuilder.LanguageCode.assyrian)
        #expect("az" == AttributedStringBuilder.LanguageCode.azerbaijani)
        #expect("bn" == AttributedStringBuilder.LanguageCode.bangla)
        #expect("be" == AttributedStringBuilder.LanguageCode.belarusian)
        #expect("brx" == AttributedStringBuilder.LanguageCode.bodo)
        #expect("bg" == AttributedStringBuilder.LanguageCode.bulgarian)
        #expect("my" == AttributedStringBuilder.LanguageCode.burmese)
        #expect("yue" == AttributedStringBuilder.LanguageCode.cantonese)
        #expect("ca" == AttributedStringBuilder.LanguageCode.catalan)
        #expect("chr" == AttributedStringBuilder.LanguageCode.cherokee)
        #expect("zh" == AttributedStringBuilder.LanguageCode.chinese)
        #expect("hr" == AttributedStringBuilder.LanguageCode.croatian)
        #expect("cs" == AttributedStringBuilder.LanguageCode.czech)
        #expect("da" == AttributedStringBuilder.LanguageCode.danish)
        #expect("dv" == AttributedStringBuilder.LanguageCode.dhivehi)
        #expect("doi" == AttributedStringBuilder.LanguageCode.dogri)
        #expect("nl" == AttributedStringBuilder.LanguageCode.dutch)
        #expect("dz" == AttributedStringBuilder.LanguageCode.dzongkha)
        #expect("en" == AttributedStringBuilder.LanguageCode.english)
        #expect("et" == AttributedStringBuilder.LanguageCode.estonian)
        #expect("fo" == AttributedStringBuilder.LanguageCode.faroese)
        #expect("fi" == AttributedStringBuilder.LanguageCode.finnish)
        #expect("fr" == AttributedStringBuilder.LanguageCode.french)
        #expect("ff" == AttributedStringBuilder.LanguageCode.fula)
        #expect("ka" == AttributedStringBuilder.LanguageCode.georgian)
        #expect("de" == AttributedStringBuilder.LanguageCode.german)
        #expect("el" == AttributedStringBuilder.LanguageCode.greek)
        #expect("gu" == AttributedStringBuilder.LanguageCode.gujarati)
        #expect("haw" == AttributedStringBuilder.LanguageCode.hawaiian)
        #expect("he" == AttributedStringBuilder.LanguageCode.hebrew)
        #expect("hi" == AttributedStringBuilder.LanguageCode.hindi)
        #expect("hu" == AttributedStringBuilder.LanguageCode.hungarian)
        #expect("is" == AttributedStringBuilder.LanguageCode.icelandic)
        #expect("ig" == AttributedStringBuilder.LanguageCode.igbo)
        #expect("id" == AttributedStringBuilder.LanguageCode.indonesian)
        #expect("ga" == AttributedStringBuilder.LanguageCode.irish)
        #expect("it" == AttributedStringBuilder.LanguageCode.italian)
        #expect("ja" == AttributedStringBuilder.LanguageCode.japanese)
        #expect("kn" == AttributedStringBuilder.LanguageCode.kannada)
        #expect("ks" == AttributedStringBuilder.LanguageCode.kashmiri)
        #expect("kk" == AttributedStringBuilder.LanguageCode.kazakh)
        #expect("km" == AttributedStringBuilder.LanguageCode.khmer)
        #expect("kok" == AttributedStringBuilder.LanguageCode.konkani)
        #expect("ko" == AttributedStringBuilder.LanguageCode.korean)
        #expect("ku" == AttributedStringBuilder.LanguageCode.kurdish)
        #expect("ckb" == AttributedStringBuilder.LanguageCode.kurdishSorani)
        #expect("ky" == AttributedStringBuilder.LanguageCode.kyrgyz)
        #expect("lo" == AttributedStringBuilder.LanguageCode.lao)
        #expect("lv" == AttributedStringBuilder.LanguageCode.latvian)
        #expect("lt" == AttributedStringBuilder.LanguageCode.lithuanian)
        #expect("mk" == AttributedStringBuilder.LanguageCode.macedonian)
        #expect("mai" == AttributedStringBuilder.LanguageCode.maithili)
        #expect("ms" == AttributedStringBuilder.LanguageCode.malay)
        #expect("ml" == AttributedStringBuilder.LanguageCode.malayalam)
        #expect("mt" == AttributedStringBuilder.LanguageCode.maltese)
        #expect("mni" == AttributedStringBuilder.LanguageCode.manipuri)
        #expect("mr" == AttributedStringBuilder.LanguageCode.marathi)
        #expect("mn" == AttributedStringBuilder.LanguageCode.mongolian)
        #expect("mi" == AttributedStringBuilder.LanguageCode.māori)
        #expect("nv" == AttributedStringBuilder.LanguageCode.navajo)
        #expect("ne" == AttributedStringBuilder.LanguageCode.nepali)
        #expect("no" == AttributedStringBuilder.LanguageCode.norwegian)
        #expect("nb" == AttributedStringBuilder.LanguageCode.norwegianBokmål)
        #expect("nn" == AttributedStringBuilder.LanguageCode.norwegianNynorsk)
        #expect("or" == AttributedStringBuilder.LanguageCode.odia)
        #expect("ps" == AttributedStringBuilder.LanguageCode.pashto)
        #expect("fa" == AttributedStringBuilder.LanguageCode.persian)
        #expect("pl" == AttributedStringBuilder.LanguageCode.polish)
        #expect("pt" == AttributedStringBuilder.LanguageCode.portuguese)
        #expect("rhg" == AttributedStringBuilder.LanguageCode.rohingya)
        #expect("ro" == AttributedStringBuilder.LanguageCode.romanian)
        #expect("ru" == AttributedStringBuilder.LanguageCode.russian)
        #expect("sm" == AttributedStringBuilder.LanguageCode.samoan)
        #expect("sa" == AttributedStringBuilder.LanguageCode.sanskrit)
        #expect("sat" == AttributedStringBuilder.LanguageCode.santali)
        #expect("sr" == AttributedStringBuilder.LanguageCode.serbian)
        #expect("sd" == AttributedStringBuilder.LanguageCode.sindhi)
        #expect("si" == AttributedStringBuilder.LanguageCode.sinhala)
        #expect("sk" == AttributedStringBuilder.LanguageCode.slovak)
        #expect("sl" == AttributedStringBuilder.LanguageCode.slovenian)
        #expect("es" == AttributedStringBuilder.LanguageCode.spanish)
        #expect("sw" == AttributedStringBuilder.LanguageCode.swahili)
        #expect("sv" == AttributedStringBuilder.LanguageCode.swedish)
        #expect("tl" == AttributedStringBuilder.LanguageCode.tagalog)
        #expect("tg" == AttributedStringBuilder.LanguageCode.tajik)
        #expect("ta" == AttributedStringBuilder.LanguageCode.tamil)
        #expect("te" == AttributedStringBuilder.LanguageCode.telugu)
        #expect("th" == AttributedStringBuilder.LanguageCode.thai)
        #expect("bo" == AttributedStringBuilder.LanguageCode.tibetan)
        #expect("to" == AttributedStringBuilder.LanguageCode.tongan)
        #expect("tr" == AttributedStringBuilder.LanguageCode.turkish)
        #expect("tk" == AttributedStringBuilder.LanguageCode.turkmen)
        #expect("uk" == AttributedStringBuilder.LanguageCode.ukrainian)
        #expect("ur" == AttributedStringBuilder.LanguageCode.urdu)
        #expect("ug" == AttributedStringBuilder.LanguageCode.uyghur)
        #expect("uz" == AttributedStringBuilder.LanguageCode.uzbek)
        #expect("vi" == AttributedStringBuilder.LanguageCode.vietnamese)
        #expect("cy" == AttributedStringBuilder.LanguageCode.welsh)
        #expect("yi" == AttributedStringBuilder.LanguageCode.yiddish)

        #expect("mul" == AttributedStringBuilder.LanguageCode.multiple)
        #expect("zxx" == AttributedStringBuilder.LanguageCode.unavailable)
        #expect("mis" == AttributedStringBuilder.LanguageCode.uncoded)
        #expect("und" == AttributedStringBuilder.LanguageCode.unidentified)

        #expect("abcdefghijklmnopqrstuvwxyz" == AttributedStringBuilder.LanguageCode.unknown)
    }

    @Test
    @available(macOS 13, iOS 16, tvOS 16, watchOS 9, *)
    func languageCodes() {
        #expect(AttributedStringBuilder.LanguageCode.ainu.rawValue == Locale.LanguageCode.ainu.identifier)
        #expect(AttributedStringBuilder.LanguageCode.albanian.rawValue == Locale.LanguageCode.albanian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.amharic.rawValue == Locale.LanguageCode.amharic.identifier)
        #expect(AttributedStringBuilder.LanguageCode.apacheWestern.rawValue == Locale.LanguageCode.apacheWestern.identifier)
        #expect(AttributedStringBuilder.LanguageCode.arabic.rawValue == Locale.LanguageCode.arabic.identifier)
        #expect(AttributedStringBuilder.LanguageCode.armenian.rawValue == Locale.LanguageCode.armenian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.assamese.rawValue == Locale.LanguageCode.assamese.identifier)
        #expect(AttributedStringBuilder.LanguageCode.assyrian.rawValue == Locale.LanguageCode.assyrian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.azerbaijani.rawValue == Locale.LanguageCode.azerbaijani.identifier)
        #expect(AttributedStringBuilder.LanguageCode.bangla.rawValue == Locale.LanguageCode.bangla.identifier)
        #expect(AttributedStringBuilder.LanguageCode.belarusian.rawValue == Locale.LanguageCode.belarusian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.bodo.rawValue == Locale.LanguageCode.bodo.identifier)
        #expect(AttributedStringBuilder.LanguageCode.bulgarian.rawValue == Locale.LanguageCode.bulgarian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.burmese.rawValue == Locale.LanguageCode.burmese.identifier)
        #expect(AttributedStringBuilder.LanguageCode.cantonese.rawValue == Locale.LanguageCode.cantonese.identifier)
        #expect(AttributedStringBuilder.LanguageCode.catalan.rawValue == Locale.LanguageCode.catalan.identifier)
        #expect(AttributedStringBuilder.LanguageCode.cherokee.rawValue == Locale.LanguageCode.cherokee.identifier)
        #expect(AttributedStringBuilder.LanguageCode.chinese.rawValue == Locale.LanguageCode.chinese.identifier)
        #expect(AttributedStringBuilder.LanguageCode.croatian.rawValue == Locale.LanguageCode.croatian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.czech.rawValue == Locale.LanguageCode.czech.identifier)
        #expect(AttributedStringBuilder.LanguageCode.danish.rawValue == Locale.LanguageCode.danish.identifier)
        #expect(AttributedStringBuilder.LanguageCode.dhivehi.rawValue == Locale.LanguageCode.dhivehi.identifier)
        #expect(AttributedStringBuilder.LanguageCode.dogri.rawValue == Locale.LanguageCode.dogri.identifier)
        #expect(AttributedStringBuilder.LanguageCode.dutch.rawValue == Locale.LanguageCode.dutch.identifier)
        #expect(AttributedStringBuilder.LanguageCode.dzongkha.rawValue == Locale.LanguageCode.dzongkha.identifier)
        #expect(AttributedStringBuilder.LanguageCode.english.rawValue == Locale.LanguageCode.english.identifier)
        #expect(AttributedStringBuilder.LanguageCode.estonian.rawValue == Locale.LanguageCode.estonian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.faroese.rawValue == Locale.LanguageCode.faroese.identifier)
        #expect(AttributedStringBuilder.LanguageCode.finnish.rawValue == Locale.LanguageCode.finnish.identifier)
        #expect(AttributedStringBuilder.LanguageCode.french.rawValue == Locale.LanguageCode.french.identifier)
        #expect(AttributedStringBuilder.LanguageCode.fula.rawValue == Locale.LanguageCode.fula.identifier)
        #expect(AttributedStringBuilder.LanguageCode.georgian.rawValue == Locale.LanguageCode.georgian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.german.rawValue == Locale.LanguageCode.german.identifier)
        #expect(AttributedStringBuilder.LanguageCode.greek.rawValue == Locale.LanguageCode.greek.identifier)
        #expect(AttributedStringBuilder.LanguageCode.gujarati.rawValue == Locale.LanguageCode.gujarati.identifier)
        #expect(AttributedStringBuilder.LanguageCode.hawaiian.rawValue == Locale.LanguageCode.hawaiian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.hebrew.rawValue == Locale.LanguageCode.hebrew.identifier)
        #expect(AttributedStringBuilder.LanguageCode.hindi.rawValue == Locale.LanguageCode.hindi.identifier)
        #expect(AttributedStringBuilder.LanguageCode.hungarian.rawValue == Locale.LanguageCode.hungarian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.icelandic.rawValue == Locale.LanguageCode.icelandic.identifier)
        #expect(AttributedStringBuilder.LanguageCode.igbo.rawValue == Locale.LanguageCode.igbo.identifier)
        #expect(AttributedStringBuilder.LanguageCode.indonesian.rawValue == Locale.LanguageCode.indonesian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.irish.rawValue == Locale.LanguageCode.irish.identifier)
        #expect(AttributedStringBuilder.LanguageCode.italian.rawValue == Locale.LanguageCode.italian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.japanese.rawValue == Locale.LanguageCode.japanese.identifier)
        #expect(AttributedStringBuilder.LanguageCode.kannada.rawValue == Locale.LanguageCode.kannada.identifier)
        #expect(AttributedStringBuilder.LanguageCode.kashmiri.rawValue == Locale.LanguageCode.kashmiri.identifier)
        #expect(AttributedStringBuilder.LanguageCode.kazakh.rawValue == Locale.LanguageCode.kazakh.identifier)
        #expect(AttributedStringBuilder.LanguageCode.khmer.rawValue == Locale.LanguageCode.khmer.identifier)
        #expect(AttributedStringBuilder.LanguageCode.konkani.rawValue == Locale.LanguageCode.konkani.identifier)
        #expect(AttributedStringBuilder.LanguageCode.korean.rawValue == Locale.LanguageCode.korean.identifier)
        #expect(AttributedStringBuilder.LanguageCode.kurdish.rawValue == Locale.LanguageCode.kurdish.identifier)
        #expect(AttributedStringBuilder.LanguageCode.kurdishSorani.rawValue == Locale.LanguageCode.kurdishSorani.identifier)
        #expect(AttributedStringBuilder.LanguageCode.kyrgyz.rawValue == Locale.LanguageCode.kyrgyz.identifier)
        #expect(AttributedStringBuilder.LanguageCode.lao.rawValue == Locale.LanguageCode.lao.identifier)
        #expect(AttributedStringBuilder.LanguageCode.latvian.rawValue == Locale.LanguageCode.latvian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.lithuanian.rawValue == Locale.LanguageCode.lithuanian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.macedonian.rawValue == Locale.LanguageCode.macedonian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.maithili.rawValue == Locale.LanguageCode.maithili.identifier)
        #expect(AttributedStringBuilder.LanguageCode.malay.rawValue == Locale.LanguageCode.malay.identifier)
        #expect(AttributedStringBuilder.LanguageCode.malayalam.rawValue == Locale.LanguageCode.malayalam.identifier)
        #expect(AttributedStringBuilder.LanguageCode.maltese.rawValue == Locale.LanguageCode.maltese.identifier)
        #expect(AttributedStringBuilder.LanguageCode.manipuri.rawValue == Locale.LanguageCode.manipuri.identifier)
        #expect(AttributedStringBuilder.LanguageCode.marathi.rawValue == Locale.LanguageCode.marathi.identifier)
        #expect(AttributedStringBuilder.LanguageCode.mongolian.rawValue == Locale.LanguageCode.mongolian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.māori.rawValue == Locale.LanguageCode.māori.identifier)
        #expect(AttributedStringBuilder.LanguageCode.navajo.rawValue == Locale.LanguageCode.navajo.identifier)
        #expect(AttributedStringBuilder.LanguageCode.nepali.rawValue == Locale.LanguageCode.nepali.identifier)
        #expect(AttributedStringBuilder.LanguageCode.norwegian.rawValue == Locale.LanguageCode.norwegian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.norwegianBokmål.rawValue == Locale.LanguageCode.norwegianBokmål.identifier)
        #expect(AttributedStringBuilder.LanguageCode.norwegianNynorsk.rawValue == Locale.LanguageCode.norwegianNynorsk.identifier)
        #expect(AttributedStringBuilder.LanguageCode.odia.rawValue == Locale.LanguageCode.odia.identifier)
        #expect(AttributedStringBuilder.LanguageCode.pashto.rawValue == Locale.LanguageCode.pashto.identifier)
        #expect(AttributedStringBuilder.LanguageCode.persian.rawValue == Locale.LanguageCode.persian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.polish.rawValue == Locale.LanguageCode.polish.identifier)
        #expect(AttributedStringBuilder.LanguageCode.portuguese.rawValue == Locale.LanguageCode.portuguese.identifier)
        #expect(AttributedStringBuilder.LanguageCode.rohingya.rawValue == Locale.LanguageCode.rohingya.identifier)
        #expect(AttributedStringBuilder.LanguageCode.romanian.rawValue == Locale.LanguageCode.romanian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.russian.rawValue == Locale.LanguageCode.russian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.samoan.rawValue == Locale.LanguageCode.samoan.identifier)
        #expect(AttributedStringBuilder.LanguageCode.sanskrit.rawValue == Locale.LanguageCode.sanskrit.identifier)
        #expect(AttributedStringBuilder.LanguageCode.santali.rawValue == Locale.LanguageCode.santali.identifier)
        #expect(AttributedStringBuilder.LanguageCode.serbian.rawValue == Locale.LanguageCode.serbian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.sindhi.rawValue == Locale.LanguageCode.sindhi.identifier)
        #expect(AttributedStringBuilder.LanguageCode.sinhala.rawValue == Locale.LanguageCode.sinhala.identifier)
        #expect(AttributedStringBuilder.LanguageCode.slovak.rawValue == Locale.LanguageCode.slovak.identifier)
        #expect(AttributedStringBuilder.LanguageCode.slovenian.rawValue == Locale.LanguageCode.slovenian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.spanish.rawValue == Locale.LanguageCode.spanish.identifier)
        #expect(AttributedStringBuilder.LanguageCode.swahili.rawValue == Locale.LanguageCode.swahili.identifier)
        #expect(AttributedStringBuilder.LanguageCode.swedish.rawValue == Locale.LanguageCode.swedish.identifier)
        #expect(AttributedStringBuilder.LanguageCode.tagalog.rawValue == Locale.LanguageCode.tagalog.identifier)
        #expect(AttributedStringBuilder.LanguageCode.tajik.rawValue == Locale.LanguageCode.tajik.identifier)
        #expect(AttributedStringBuilder.LanguageCode.tamil.rawValue == Locale.LanguageCode.tamil.identifier)
        #expect(AttributedStringBuilder.LanguageCode.telugu.rawValue == Locale.LanguageCode.telugu.identifier)
        #expect(AttributedStringBuilder.LanguageCode.thai.rawValue == Locale.LanguageCode.thai.identifier)
        #expect(AttributedStringBuilder.LanguageCode.tibetan.rawValue == Locale.LanguageCode.tibetan.identifier)
        #expect(AttributedStringBuilder.LanguageCode.tongan.rawValue == Locale.LanguageCode.tongan.identifier)
        #expect(AttributedStringBuilder.LanguageCode.turkish.rawValue == Locale.LanguageCode.turkish.identifier)
        #expect(AttributedStringBuilder.LanguageCode.turkmen.rawValue == Locale.LanguageCode.turkmen.identifier)
        #expect(AttributedStringBuilder.LanguageCode.ukrainian.rawValue == Locale.LanguageCode.ukrainian.identifier)
        #expect(AttributedStringBuilder.LanguageCode.urdu.rawValue == Locale.LanguageCode.urdu.identifier)
        #expect(AttributedStringBuilder.LanguageCode.uyghur.rawValue == Locale.LanguageCode.uyghur.identifier)
        #expect(AttributedStringBuilder.LanguageCode.uzbek.rawValue == Locale.LanguageCode.uzbek.identifier)
        #expect(AttributedStringBuilder.LanguageCode.vietnamese.rawValue == Locale.LanguageCode.vietnamese.identifier)
        #expect(AttributedStringBuilder.LanguageCode.welsh.rawValue == Locale.LanguageCode.welsh.identifier)
        #expect(AttributedStringBuilder.LanguageCode.yiddish.rawValue == Locale.LanguageCode.yiddish.identifier)
        #expect(AttributedStringBuilder.LanguageCode.multiple.rawValue == Locale.LanguageCode.multiple.identifier)
        #expect(AttributedStringBuilder.LanguageCode.unavailable.rawValue == Locale.LanguageCode.unavailable.identifier)
        #expect(AttributedStringBuilder.LanguageCode.uncoded.rawValue == Locale.LanguageCode.uncoded.identifier)
        #expect(AttributedStringBuilder.LanguageCode.unidentified.rawValue == Locale.LanguageCode.unidentified.identifier)
    }
}
