import NSAttributedStringBuilder
import XCTest

final class LanguageCodeTests: XCTestCase {

    func testInitWithRawValue() {
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ain"), NSAttributedStringBuilder.LanguageCode.ainu)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "sq"), NSAttributedStringBuilder.LanguageCode.albanian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "am"), NSAttributedStringBuilder.LanguageCode.amharic)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "apw"), NSAttributedStringBuilder.LanguageCode.apacheWestern)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ar"), NSAttributedStringBuilder.LanguageCode.arabic)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "hy"), NSAttributedStringBuilder.LanguageCode.armenian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "as"), NSAttributedStringBuilder.LanguageCode.assamese)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "syr"), NSAttributedStringBuilder.LanguageCode.assyrian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "az"), NSAttributedStringBuilder.LanguageCode.azerbaijani)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "bn"), NSAttributedStringBuilder.LanguageCode.bangla)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "be"), NSAttributedStringBuilder.LanguageCode.belarusian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "brx"), NSAttributedStringBuilder.LanguageCode.bodo)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "bg"), NSAttributedStringBuilder.LanguageCode.bulgarian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "my"), NSAttributedStringBuilder.LanguageCode.burmese)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "yue"), NSAttributedStringBuilder.LanguageCode.cantonese)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ca"), NSAttributedStringBuilder.LanguageCode.catalan)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "chr"), NSAttributedStringBuilder.LanguageCode.cherokee)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "zh"), NSAttributedStringBuilder.LanguageCode.chinese)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "hr"), NSAttributedStringBuilder.LanguageCode.croatian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "cs"), NSAttributedStringBuilder.LanguageCode.czech)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "da"), NSAttributedStringBuilder.LanguageCode.danish)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "dv"), NSAttributedStringBuilder.LanguageCode.dhivehi)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "doi"), NSAttributedStringBuilder.LanguageCode.dogri)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "nl"), NSAttributedStringBuilder.LanguageCode.dutch)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "dz"), NSAttributedStringBuilder.LanguageCode.dzongkha)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "en"), NSAttributedStringBuilder.LanguageCode.english)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "et"), NSAttributedStringBuilder.LanguageCode.estonian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "fo"), NSAttributedStringBuilder.LanguageCode.faroese)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "fi"), NSAttributedStringBuilder.LanguageCode.finnish)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "fr"), NSAttributedStringBuilder.LanguageCode.french)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ff"), NSAttributedStringBuilder.LanguageCode.fula)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ka"), NSAttributedStringBuilder.LanguageCode.georgian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "de"), NSAttributedStringBuilder.LanguageCode.german)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "el"), NSAttributedStringBuilder.LanguageCode.greek)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "gu"), NSAttributedStringBuilder.LanguageCode.gujarati)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "haw"), NSAttributedStringBuilder.LanguageCode.hawaiian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "he"), NSAttributedStringBuilder.LanguageCode.hebrew)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "hi"), NSAttributedStringBuilder.LanguageCode.hindi)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "hu"), NSAttributedStringBuilder.LanguageCode.hungarian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "is"), NSAttributedStringBuilder.LanguageCode.icelandic)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ig"), NSAttributedStringBuilder.LanguageCode.igbo)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "id"), NSAttributedStringBuilder.LanguageCode.indonesian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ga"), NSAttributedStringBuilder.LanguageCode.irish)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "it"), NSAttributedStringBuilder.LanguageCode.italian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ja"), NSAttributedStringBuilder.LanguageCode.japanese)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "kn"), NSAttributedStringBuilder.LanguageCode.kannada)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ks"), NSAttributedStringBuilder.LanguageCode.kashmiri)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "kk"), NSAttributedStringBuilder.LanguageCode.kazakh)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "km"), NSAttributedStringBuilder.LanguageCode.khmer)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "kok"), NSAttributedStringBuilder.LanguageCode.konkani)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ko"), NSAttributedStringBuilder.LanguageCode.korean)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ku"), NSAttributedStringBuilder.LanguageCode.kurdish)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ckb"), NSAttributedStringBuilder.LanguageCode.kurdishSorani)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ky"), NSAttributedStringBuilder.LanguageCode.kyrgyz)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "lo"), NSAttributedStringBuilder.LanguageCode.lao)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "lv"), NSAttributedStringBuilder.LanguageCode.latvian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "lt"), NSAttributedStringBuilder.LanguageCode.lithuanian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "mk"), NSAttributedStringBuilder.LanguageCode.macedonian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "mai"), NSAttributedStringBuilder.LanguageCode.maithili)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ms"), NSAttributedStringBuilder.LanguageCode.malay)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ml"), NSAttributedStringBuilder.LanguageCode.malayalam)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "mt"), NSAttributedStringBuilder.LanguageCode.maltese)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "mni"), NSAttributedStringBuilder.LanguageCode.manipuri)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "mr"), NSAttributedStringBuilder.LanguageCode.marathi)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "mn"), NSAttributedStringBuilder.LanguageCode.mongolian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "mi"), NSAttributedStringBuilder.LanguageCode.māori)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "nv"), NSAttributedStringBuilder.LanguageCode.navajo)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ne"), NSAttributedStringBuilder.LanguageCode.nepali)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "no"), NSAttributedStringBuilder.LanguageCode.norwegian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "nb"), NSAttributedStringBuilder.LanguageCode.norwegianBokmål)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "nn"), NSAttributedStringBuilder.LanguageCode.norwegianNynorsk)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "or"), NSAttributedStringBuilder.LanguageCode.odia)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ps"), NSAttributedStringBuilder.LanguageCode.pashto)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "fa"), NSAttributedStringBuilder.LanguageCode.persian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "pl"), NSAttributedStringBuilder.LanguageCode.polish)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "pt"), NSAttributedStringBuilder.LanguageCode.portuguese)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "rhg"), NSAttributedStringBuilder.LanguageCode.rohingya)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ro"), NSAttributedStringBuilder.LanguageCode.romanian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ru"), NSAttributedStringBuilder.LanguageCode.russian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "sm"), NSAttributedStringBuilder.LanguageCode.samoan)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "sa"), NSAttributedStringBuilder.LanguageCode.sanskrit)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "sat"), NSAttributedStringBuilder.LanguageCode.santali)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "sr"), NSAttributedStringBuilder.LanguageCode.serbian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "sd"), NSAttributedStringBuilder.LanguageCode.sindhi)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "si"), NSAttributedStringBuilder.LanguageCode.sinhala)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "sk"), NSAttributedStringBuilder.LanguageCode.slovak)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "sl"), NSAttributedStringBuilder.LanguageCode.slovenian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "es"), NSAttributedStringBuilder.LanguageCode.spanish)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "sw"), NSAttributedStringBuilder.LanguageCode.swahili)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "sv"), NSAttributedStringBuilder.LanguageCode.swedish)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "tl"), NSAttributedStringBuilder.LanguageCode.tagalog)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "tg"), NSAttributedStringBuilder.LanguageCode.tajik)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ta"), NSAttributedStringBuilder.LanguageCode.tamil)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "te"), NSAttributedStringBuilder.LanguageCode.telugu)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "th"), NSAttributedStringBuilder.LanguageCode.thai)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "bo"), NSAttributedStringBuilder.LanguageCode.tibetan)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "to"), NSAttributedStringBuilder.LanguageCode.tongan)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "tr"), NSAttributedStringBuilder.LanguageCode.turkish)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "tk"), NSAttributedStringBuilder.LanguageCode.turkmen)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "uk"), NSAttributedStringBuilder.LanguageCode.ukrainian)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ur"), NSAttributedStringBuilder.LanguageCode.urdu)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "ug"), NSAttributedStringBuilder.LanguageCode.uyghur)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "uz"), NSAttributedStringBuilder.LanguageCode.uzbek)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "vi"), NSAttributedStringBuilder.LanguageCode.vietnamese)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "cy"), NSAttributedStringBuilder.LanguageCode.welsh)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "yi"), NSAttributedStringBuilder.LanguageCode.yiddish)

        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "mul"), NSAttributedStringBuilder.LanguageCode.multiple)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "zxx"), NSAttributedStringBuilder.LanguageCode.unavailable)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "mis"), NSAttributedStringBuilder.LanguageCode.uncoded)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode(rawValue: "und"), NSAttributedStringBuilder.LanguageCode.unidentified)

        XCTAssertNil(NSAttributedStringBuilder.LanguageCode(rawValue: .unique()))
    }

    func testInitExpressibleByStringLiteral() {
        XCTAssertEqual("ain", NSAttributedStringBuilder.LanguageCode.ainu)
        XCTAssertEqual("sq", NSAttributedStringBuilder.LanguageCode.albanian)
        XCTAssertEqual("am", NSAttributedStringBuilder.LanguageCode.amharic)
        XCTAssertEqual("apw", NSAttributedStringBuilder.LanguageCode.apacheWestern)
        XCTAssertEqual("ar", NSAttributedStringBuilder.LanguageCode.arabic)
        XCTAssertEqual("hy", NSAttributedStringBuilder.LanguageCode.armenian)
        XCTAssertEqual("as", NSAttributedStringBuilder.LanguageCode.assamese)
        XCTAssertEqual("syr", NSAttributedStringBuilder.LanguageCode.assyrian)
        XCTAssertEqual("az", NSAttributedStringBuilder.LanguageCode.azerbaijani)
        XCTAssertEqual("bn", NSAttributedStringBuilder.LanguageCode.bangla)
        XCTAssertEqual("be", NSAttributedStringBuilder.LanguageCode.belarusian)
        XCTAssertEqual("brx", NSAttributedStringBuilder.LanguageCode.bodo)
        XCTAssertEqual("bg", NSAttributedStringBuilder.LanguageCode.bulgarian)
        XCTAssertEqual("my", NSAttributedStringBuilder.LanguageCode.burmese)
        XCTAssertEqual("yue", NSAttributedStringBuilder.LanguageCode.cantonese)
        XCTAssertEqual("ca", NSAttributedStringBuilder.LanguageCode.catalan)
        XCTAssertEqual("chr", NSAttributedStringBuilder.LanguageCode.cherokee)
        XCTAssertEqual("zh", NSAttributedStringBuilder.LanguageCode.chinese)
        XCTAssertEqual("hr", NSAttributedStringBuilder.LanguageCode.croatian)
        XCTAssertEqual("cs", NSAttributedStringBuilder.LanguageCode.czech)
        XCTAssertEqual("da", NSAttributedStringBuilder.LanguageCode.danish)
        XCTAssertEqual("dv", NSAttributedStringBuilder.LanguageCode.dhivehi)
        XCTAssertEqual("doi", NSAttributedStringBuilder.LanguageCode.dogri)
        XCTAssertEqual("nl", NSAttributedStringBuilder.LanguageCode.dutch)
        XCTAssertEqual("dz", NSAttributedStringBuilder.LanguageCode.dzongkha)
        XCTAssertEqual("en", NSAttributedStringBuilder.LanguageCode.english)
        XCTAssertEqual("et", NSAttributedStringBuilder.LanguageCode.estonian)
        XCTAssertEqual("fo", NSAttributedStringBuilder.LanguageCode.faroese)
        XCTAssertEqual("fi", NSAttributedStringBuilder.LanguageCode.finnish)
        XCTAssertEqual("fr", NSAttributedStringBuilder.LanguageCode.french)
        XCTAssertEqual("ff", NSAttributedStringBuilder.LanguageCode.fula)
        XCTAssertEqual("ka", NSAttributedStringBuilder.LanguageCode.georgian)
        XCTAssertEqual("de", NSAttributedStringBuilder.LanguageCode.german)
        XCTAssertEqual("el", NSAttributedStringBuilder.LanguageCode.greek)
        XCTAssertEqual("gu", NSAttributedStringBuilder.LanguageCode.gujarati)
        XCTAssertEqual("haw", NSAttributedStringBuilder.LanguageCode.hawaiian)
        XCTAssertEqual("he", NSAttributedStringBuilder.LanguageCode.hebrew)
        XCTAssertEqual("hi", NSAttributedStringBuilder.LanguageCode.hindi)
        XCTAssertEqual("hu", NSAttributedStringBuilder.LanguageCode.hungarian)
        XCTAssertEqual("is", NSAttributedStringBuilder.LanguageCode.icelandic)
        XCTAssertEqual("ig", NSAttributedStringBuilder.LanguageCode.igbo)
        XCTAssertEqual("id", NSAttributedStringBuilder.LanguageCode.indonesian)
        XCTAssertEqual("ga", NSAttributedStringBuilder.LanguageCode.irish)
        XCTAssertEqual("it", NSAttributedStringBuilder.LanguageCode.italian)
        XCTAssertEqual("ja", NSAttributedStringBuilder.LanguageCode.japanese)
        XCTAssertEqual("kn", NSAttributedStringBuilder.LanguageCode.kannada)
        XCTAssertEqual("ks", NSAttributedStringBuilder.LanguageCode.kashmiri)
        XCTAssertEqual("kk", NSAttributedStringBuilder.LanguageCode.kazakh)
        XCTAssertEqual("km", NSAttributedStringBuilder.LanguageCode.khmer)
        XCTAssertEqual("kok", NSAttributedStringBuilder.LanguageCode.konkani)
        XCTAssertEqual("ko", NSAttributedStringBuilder.LanguageCode.korean)
        XCTAssertEqual("ku", NSAttributedStringBuilder.LanguageCode.kurdish)
        XCTAssertEqual("ckb", NSAttributedStringBuilder.LanguageCode.kurdishSorani)
        XCTAssertEqual("ky", NSAttributedStringBuilder.LanguageCode.kyrgyz)
        XCTAssertEqual("lo", NSAttributedStringBuilder.LanguageCode.lao)
        XCTAssertEqual("lv", NSAttributedStringBuilder.LanguageCode.latvian)
        XCTAssertEqual("lt", NSAttributedStringBuilder.LanguageCode.lithuanian)
        XCTAssertEqual("mk", NSAttributedStringBuilder.LanguageCode.macedonian)
        XCTAssertEqual("mai", NSAttributedStringBuilder.LanguageCode.maithili)
        XCTAssertEqual("ms", NSAttributedStringBuilder.LanguageCode.malay)
        XCTAssertEqual("ml", NSAttributedStringBuilder.LanguageCode.malayalam)
        XCTAssertEqual("mt", NSAttributedStringBuilder.LanguageCode.maltese)
        XCTAssertEqual("mni", NSAttributedStringBuilder.LanguageCode.manipuri)
        XCTAssertEqual("mr", NSAttributedStringBuilder.LanguageCode.marathi)
        XCTAssertEqual("mn", NSAttributedStringBuilder.LanguageCode.mongolian)
        XCTAssertEqual("mi", NSAttributedStringBuilder.LanguageCode.māori)
        XCTAssertEqual("nv", NSAttributedStringBuilder.LanguageCode.navajo)
        XCTAssertEqual("ne", NSAttributedStringBuilder.LanguageCode.nepali)
        XCTAssertEqual("no", NSAttributedStringBuilder.LanguageCode.norwegian)
        XCTAssertEqual("nb", NSAttributedStringBuilder.LanguageCode.norwegianBokmål)
        XCTAssertEqual("nn", NSAttributedStringBuilder.LanguageCode.norwegianNynorsk)
        XCTAssertEqual("or", NSAttributedStringBuilder.LanguageCode.odia)
        XCTAssertEqual("ps", NSAttributedStringBuilder.LanguageCode.pashto)
        XCTAssertEqual("fa", NSAttributedStringBuilder.LanguageCode.persian)
        XCTAssertEqual("pl", NSAttributedStringBuilder.LanguageCode.polish)
        XCTAssertEqual("pt", NSAttributedStringBuilder.LanguageCode.portuguese)
        XCTAssertEqual("rhg", NSAttributedStringBuilder.LanguageCode.rohingya)
        XCTAssertEqual("ro", NSAttributedStringBuilder.LanguageCode.romanian)
        XCTAssertEqual("ru", NSAttributedStringBuilder.LanguageCode.russian)
        XCTAssertEqual("sm", NSAttributedStringBuilder.LanguageCode.samoan)
        XCTAssertEqual("sa", NSAttributedStringBuilder.LanguageCode.sanskrit)
        XCTAssertEqual("sat", NSAttributedStringBuilder.LanguageCode.santali)
        XCTAssertEqual("sr", NSAttributedStringBuilder.LanguageCode.serbian)
        XCTAssertEqual("sd", NSAttributedStringBuilder.LanguageCode.sindhi)
        XCTAssertEqual("si", NSAttributedStringBuilder.LanguageCode.sinhala)
        XCTAssertEqual("sk", NSAttributedStringBuilder.LanguageCode.slovak)
        XCTAssertEqual("sl", NSAttributedStringBuilder.LanguageCode.slovenian)
        XCTAssertEqual("es", NSAttributedStringBuilder.LanguageCode.spanish)
        XCTAssertEqual("sw", NSAttributedStringBuilder.LanguageCode.swahili)
        XCTAssertEqual("sv", NSAttributedStringBuilder.LanguageCode.swedish)
        XCTAssertEqual("tl", NSAttributedStringBuilder.LanguageCode.tagalog)
        XCTAssertEqual("tg", NSAttributedStringBuilder.LanguageCode.tajik)
        XCTAssertEqual("ta", NSAttributedStringBuilder.LanguageCode.tamil)
        XCTAssertEqual("te", NSAttributedStringBuilder.LanguageCode.telugu)
        XCTAssertEqual("th", NSAttributedStringBuilder.LanguageCode.thai)
        XCTAssertEqual("bo", NSAttributedStringBuilder.LanguageCode.tibetan)
        XCTAssertEqual("to", NSAttributedStringBuilder.LanguageCode.tongan)
        XCTAssertEqual("tr", NSAttributedStringBuilder.LanguageCode.turkish)
        XCTAssertEqual("tk", NSAttributedStringBuilder.LanguageCode.turkmen)
        XCTAssertEqual("uk", NSAttributedStringBuilder.LanguageCode.ukrainian)
        XCTAssertEqual("ur", NSAttributedStringBuilder.LanguageCode.urdu)
        XCTAssertEqual("ug", NSAttributedStringBuilder.LanguageCode.uyghur)
        XCTAssertEqual("uz", NSAttributedStringBuilder.LanguageCode.uzbek)
        XCTAssertEqual("vi", NSAttributedStringBuilder.LanguageCode.vietnamese)
        XCTAssertEqual("cy", NSAttributedStringBuilder.LanguageCode.welsh)
        XCTAssertEqual("yi", NSAttributedStringBuilder.LanguageCode.yiddish)

        XCTAssertEqual("mul", NSAttributedStringBuilder.LanguageCode.multiple)
        XCTAssertEqual("zxx", NSAttributedStringBuilder.LanguageCode.unavailable)
        XCTAssertEqual("mis", NSAttributedStringBuilder.LanguageCode.uncoded)
        XCTAssertEqual("und", NSAttributedStringBuilder.LanguageCode.unidentified)

        XCTAssertEqual("abcdefghijklmnopqrstuvwxyz", NSAttributedStringBuilder.LanguageCode.unknown)
    }

    @available(macOS 13, iOS 16, tvOS 16, watchOS 9, *)
    func testLanguageCodes() {
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.ainu.rawValue, Locale.LanguageCode.ainu.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.albanian.rawValue, Locale.LanguageCode.albanian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.amharic.rawValue, Locale.LanguageCode.amharic.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.apacheWestern.rawValue, Locale.LanguageCode.apacheWestern.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.arabic.rawValue, Locale.LanguageCode.arabic.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.armenian.rawValue, Locale.LanguageCode.armenian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.assamese.rawValue, Locale.LanguageCode.assamese.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.assyrian.rawValue, Locale.LanguageCode.assyrian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.azerbaijani.rawValue, Locale.LanguageCode.azerbaijani.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.bangla.rawValue, Locale.LanguageCode.bangla.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.belarusian.rawValue, Locale.LanguageCode.belarusian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.bodo.rawValue, Locale.LanguageCode.bodo.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.bulgarian.rawValue, Locale.LanguageCode.bulgarian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.burmese.rawValue, Locale.LanguageCode.burmese.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.cantonese.rawValue, Locale.LanguageCode.cantonese.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.catalan.rawValue, Locale.LanguageCode.catalan.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.cherokee.rawValue, Locale.LanguageCode.cherokee.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.chinese.rawValue, Locale.LanguageCode.chinese.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.croatian.rawValue, Locale.LanguageCode.croatian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.czech.rawValue, Locale.LanguageCode.czech.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.danish.rawValue, Locale.LanguageCode.danish.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.dhivehi.rawValue, Locale.LanguageCode.dhivehi.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.dogri.rawValue, Locale.LanguageCode.dogri.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.dutch.rawValue, Locale.LanguageCode.dutch.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.dzongkha.rawValue, Locale.LanguageCode.dzongkha.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.english.rawValue, Locale.LanguageCode.english.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.estonian.rawValue, Locale.LanguageCode.estonian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.faroese.rawValue, Locale.LanguageCode.faroese.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.finnish.rawValue, Locale.LanguageCode.finnish.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.french.rawValue, Locale.LanguageCode.french.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.fula.rawValue, Locale.LanguageCode.fula.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.georgian.rawValue, Locale.LanguageCode.georgian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.german.rawValue, Locale.LanguageCode.german.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.greek.rawValue, Locale.LanguageCode.greek.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.gujarati.rawValue, Locale.LanguageCode.gujarati.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.hawaiian.rawValue, Locale.LanguageCode.hawaiian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.hebrew.rawValue, Locale.LanguageCode.hebrew.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.hindi.rawValue, Locale.LanguageCode.hindi.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.hungarian.rawValue, Locale.LanguageCode.hungarian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.icelandic.rawValue, Locale.LanguageCode.icelandic.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.igbo.rawValue, Locale.LanguageCode.igbo.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.indonesian.rawValue, Locale.LanguageCode.indonesian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.irish.rawValue, Locale.LanguageCode.irish.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.italian.rawValue, Locale.LanguageCode.italian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.japanese.rawValue, Locale.LanguageCode.japanese.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.kannada.rawValue, Locale.LanguageCode.kannada.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.kashmiri.rawValue, Locale.LanguageCode.kashmiri.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.kazakh.rawValue, Locale.LanguageCode.kazakh.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.khmer.rawValue, Locale.LanguageCode.khmer.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.konkani.rawValue, Locale.LanguageCode.konkani.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.korean.rawValue, Locale.LanguageCode.korean.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.kurdish.rawValue, Locale.LanguageCode.kurdish.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.kurdishSorani.rawValue, Locale.LanguageCode.kurdishSorani.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.kyrgyz.rawValue, Locale.LanguageCode.kyrgyz.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.lao.rawValue, Locale.LanguageCode.lao.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.latvian.rawValue, Locale.LanguageCode.latvian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.lithuanian.rawValue, Locale.LanguageCode.lithuanian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.macedonian.rawValue, Locale.LanguageCode.macedonian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.maithili.rawValue, Locale.LanguageCode.maithili.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.malay.rawValue, Locale.LanguageCode.malay.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.malayalam.rawValue, Locale.LanguageCode.malayalam.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.maltese.rawValue, Locale.LanguageCode.maltese.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.manipuri.rawValue, Locale.LanguageCode.manipuri.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.marathi.rawValue, Locale.LanguageCode.marathi.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.mongolian.rawValue, Locale.LanguageCode.mongolian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.māori.rawValue, Locale.LanguageCode.māori.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.navajo.rawValue, Locale.LanguageCode.navajo.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.nepali.rawValue, Locale.LanguageCode.nepali.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.norwegian.rawValue, Locale.LanguageCode.norwegian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.norwegianBokmål.rawValue, Locale.LanguageCode.norwegianBokmål.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.norwegianNynorsk.rawValue, Locale.LanguageCode.norwegianNynorsk.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.odia.rawValue, Locale.LanguageCode.odia.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.pashto.rawValue, Locale.LanguageCode.pashto.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.persian.rawValue, Locale.LanguageCode.persian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.polish.rawValue, Locale.LanguageCode.polish.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.portuguese.rawValue, Locale.LanguageCode.portuguese.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.rohingya.rawValue, Locale.LanguageCode.rohingya.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.romanian.rawValue, Locale.LanguageCode.romanian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.russian.rawValue, Locale.LanguageCode.russian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.samoan.rawValue, Locale.LanguageCode.samoan.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.sanskrit.rawValue, Locale.LanguageCode.sanskrit.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.santali.rawValue, Locale.LanguageCode.santali.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.serbian.rawValue, Locale.LanguageCode.serbian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.sindhi.rawValue, Locale.LanguageCode.sindhi.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.sinhala.rawValue, Locale.LanguageCode.sinhala.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.slovak.rawValue, Locale.LanguageCode.slovak.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.slovenian.rawValue, Locale.LanguageCode.slovenian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.spanish.rawValue, Locale.LanguageCode.spanish.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.swahili.rawValue, Locale.LanguageCode.swahili.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.swedish.rawValue, Locale.LanguageCode.swedish.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.tagalog.rawValue, Locale.LanguageCode.tagalog.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.tajik.rawValue, Locale.LanguageCode.tajik.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.tamil.rawValue, Locale.LanguageCode.tamil.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.telugu.rawValue, Locale.LanguageCode.telugu.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.thai.rawValue, Locale.LanguageCode.thai.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.tibetan.rawValue, Locale.LanguageCode.tibetan.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.tongan.rawValue, Locale.LanguageCode.tongan.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.turkish.rawValue, Locale.LanguageCode.turkish.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.turkmen.rawValue, Locale.LanguageCode.turkmen.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.ukrainian.rawValue, Locale.LanguageCode.ukrainian.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.urdu.rawValue, Locale.LanguageCode.urdu.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.uyghur.rawValue, Locale.LanguageCode.uyghur.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.uzbek.rawValue, Locale.LanguageCode.uzbek.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.vietnamese.rawValue, Locale.LanguageCode.vietnamese.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.welsh.rawValue, Locale.LanguageCode.welsh.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.yiddish.rawValue, Locale.LanguageCode.yiddish.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.multiple.rawValue, Locale.LanguageCode.multiple.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.unavailable.rawValue, Locale.LanguageCode.unavailable.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.uncoded.rawValue, Locale.LanguageCode.uncoded.identifier)
        XCTAssertEqual(NSAttributedStringBuilder.LanguageCode.unidentified.rawValue, Locale.LanguageCode.unidentified.identifier)
    }
}
