import Foundation
import NSAttributedStringBuilder
import Testing

@Suite
struct LanguageCodeTests {

    @Test
    func initWithRawValue() {
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ain") == NSAttributedStringBuilder.LanguageCode.ainu)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "sq") == NSAttributedStringBuilder.LanguageCode.albanian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "am") == NSAttributedStringBuilder.LanguageCode.amharic)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "apw") == NSAttributedStringBuilder.LanguageCode.apacheWestern)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ar") == NSAttributedStringBuilder.LanguageCode.arabic)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "hy") == NSAttributedStringBuilder.LanguageCode.armenian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "as") == NSAttributedStringBuilder.LanguageCode.assamese)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "syr") == NSAttributedStringBuilder.LanguageCode.assyrian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "az") == NSAttributedStringBuilder.LanguageCode.azerbaijani)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "bn") == NSAttributedStringBuilder.LanguageCode.bangla)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "be") == NSAttributedStringBuilder.LanguageCode.belarusian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "brx") == NSAttributedStringBuilder.LanguageCode.bodo)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "bg") == NSAttributedStringBuilder.LanguageCode.bulgarian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "my") == NSAttributedStringBuilder.LanguageCode.burmese)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "yue") == NSAttributedStringBuilder.LanguageCode.cantonese)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ca") == NSAttributedStringBuilder.LanguageCode.catalan)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "chr") == NSAttributedStringBuilder.LanguageCode.cherokee)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "zh") == NSAttributedStringBuilder.LanguageCode.chinese)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "hr") == NSAttributedStringBuilder.LanguageCode.croatian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "cs") == NSAttributedStringBuilder.LanguageCode.czech)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "da") == NSAttributedStringBuilder.LanguageCode.danish)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "dv") == NSAttributedStringBuilder.LanguageCode.dhivehi)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "doi") == NSAttributedStringBuilder.LanguageCode.dogri)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "nl") == NSAttributedStringBuilder.LanguageCode.dutch)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "dz") == NSAttributedStringBuilder.LanguageCode.dzongkha)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "en") == NSAttributedStringBuilder.LanguageCode.english)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "et") == NSAttributedStringBuilder.LanguageCode.estonian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "fo") == NSAttributedStringBuilder.LanguageCode.faroese)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "fi") == NSAttributedStringBuilder.LanguageCode.finnish)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "fr") == NSAttributedStringBuilder.LanguageCode.french)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ff") == NSAttributedStringBuilder.LanguageCode.fula)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ka") == NSAttributedStringBuilder.LanguageCode.georgian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "de") == NSAttributedStringBuilder.LanguageCode.german)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "el") == NSAttributedStringBuilder.LanguageCode.greek)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "gu") == NSAttributedStringBuilder.LanguageCode.gujarati)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "haw") == NSAttributedStringBuilder.LanguageCode.hawaiian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "he") == NSAttributedStringBuilder.LanguageCode.hebrew)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "hi") == NSAttributedStringBuilder.LanguageCode.hindi)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "hu") == NSAttributedStringBuilder.LanguageCode.hungarian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "is") == NSAttributedStringBuilder.LanguageCode.icelandic)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ig") == NSAttributedStringBuilder.LanguageCode.igbo)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "id") == NSAttributedStringBuilder.LanguageCode.indonesian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ga") == NSAttributedStringBuilder.LanguageCode.irish)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "it") == NSAttributedStringBuilder.LanguageCode.italian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ja") == NSAttributedStringBuilder.LanguageCode.japanese)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "kn") == NSAttributedStringBuilder.LanguageCode.kannada)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ks") == NSAttributedStringBuilder.LanguageCode.kashmiri)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "kk") == NSAttributedStringBuilder.LanguageCode.kazakh)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "km") == NSAttributedStringBuilder.LanguageCode.khmer)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "kok") == NSAttributedStringBuilder.LanguageCode.konkani)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ko") == NSAttributedStringBuilder.LanguageCode.korean)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ku") == NSAttributedStringBuilder.LanguageCode.kurdish)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ckb") == NSAttributedStringBuilder.LanguageCode.kurdishSorani)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ky") == NSAttributedStringBuilder.LanguageCode.kyrgyz)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "lo") == NSAttributedStringBuilder.LanguageCode.lao)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "lv") == NSAttributedStringBuilder.LanguageCode.latvian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "lt") == NSAttributedStringBuilder.LanguageCode.lithuanian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "mk") == NSAttributedStringBuilder.LanguageCode.macedonian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "mai") == NSAttributedStringBuilder.LanguageCode.maithili)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ms") == NSAttributedStringBuilder.LanguageCode.malay)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ml") == NSAttributedStringBuilder.LanguageCode.malayalam)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "mt") == NSAttributedStringBuilder.LanguageCode.maltese)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "mni") == NSAttributedStringBuilder.LanguageCode.manipuri)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "mr") == NSAttributedStringBuilder.LanguageCode.marathi)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "mn") == NSAttributedStringBuilder.LanguageCode.mongolian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "mi") == NSAttributedStringBuilder.LanguageCode.māori)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "nv") == NSAttributedStringBuilder.LanguageCode.navajo)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ne") == NSAttributedStringBuilder.LanguageCode.nepali)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "no") == NSAttributedStringBuilder.LanguageCode.norwegian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "nb") == NSAttributedStringBuilder.LanguageCode.norwegianBokmål)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "nn") == NSAttributedStringBuilder.LanguageCode.norwegianNynorsk)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "or") == NSAttributedStringBuilder.LanguageCode.odia)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ps") == NSAttributedStringBuilder.LanguageCode.pashto)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "fa") == NSAttributedStringBuilder.LanguageCode.persian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "pl") == NSAttributedStringBuilder.LanguageCode.polish)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "pt") == NSAttributedStringBuilder.LanguageCode.portuguese)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "rhg") == NSAttributedStringBuilder.LanguageCode.rohingya)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ro") == NSAttributedStringBuilder.LanguageCode.romanian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ru") == NSAttributedStringBuilder.LanguageCode.russian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "sm") == NSAttributedStringBuilder.LanguageCode.samoan)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "sa") == NSAttributedStringBuilder.LanguageCode.sanskrit)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "sat") == NSAttributedStringBuilder.LanguageCode.santali)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "sr") == NSAttributedStringBuilder.LanguageCode.serbian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "sd") == NSAttributedStringBuilder.LanguageCode.sindhi)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "si") == NSAttributedStringBuilder.LanguageCode.sinhala)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "sk") == NSAttributedStringBuilder.LanguageCode.slovak)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "sl") == NSAttributedStringBuilder.LanguageCode.slovenian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "es") == NSAttributedStringBuilder.LanguageCode.spanish)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "sw") == NSAttributedStringBuilder.LanguageCode.swahili)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "sv") == NSAttributedStringBuilder.LanguageCode.swedish)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "tl") == NSAttributedStringBuilder.LanguageCode.tagalog)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "tg") == NSAttributedStringBuilder.LanguageCode.tajik)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ta") == NSAttributedStringBuilder.LanguageCode.tamil)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "te") == NSAttributedStringBuilder.LanguageCode.telugu)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "th") == NSAttributedStringBuilder.LanguageCode.thai)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "bo") == NSAttributedStringBuilder.LanguageCode.tibetan)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "to") == NSAttributedStringBuilder.LanguageCode.tongan)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "tr") == NSAttributedStringBuilder.LanguageCode.turkish)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "tk") == NSAttributedStringBuilder.LanguageCode.turkmen)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "uk") == NSAttributedStringBuilder.LanguageCode.ukrainian)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ur") == NSAttributedStringBuilder.LanguageCode.urdu)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "ug") == NSAttributedStringBuilder.LanguageCode.uyghur)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "uz") == NSAttributedStringBuilder.LanguageCode.uzbek)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "vi") == NSAttributedStringBuilder.LanguageCode.vietnamese)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "cy") == NSAttributedStringBuilder.LanguageCode.welsh)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "yi") == NSAttributedStringBuilder.LanguageCode.yiddish)

        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "mul") == NSAttributedStringBuilder.LanguageCode.multiple)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "zxx") == NSAttributedStringBuilder.LanguageCode.unavailable)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "mis") == NSAttributedStringBuilder.LanguageCode.uncoded)
        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: "und") == NSAttributedStringBuilder.LanguageCode.unidentified)

        #expect(NSAttributedStringBuilder.LanguageCode(rawValue: .unique()) == nil)
    }

    @Test
    func initExpressibleByStringLiteral() {
        #expect("ain" == NSAttributedStringBuilder.LanguageCode.ainu)
        #expect("sq" == NSAttributedStringBuilder.LanguageCode.albanian)
        #expect("am" == NSAttributedStringBuilder.LanguageCode.amharic)
        #expect("apw" == NSAttributedStringBuilder.LanguageCode.apacheWestern)
        #expect("ar" == NSAttributedStringBuilder.LanguageCode.arabic)
        #expect("hy" == NSAttributedStringBuilder.LanguageCode.armenian)
        #expect("as" == NSAttributedStringBuilder.LanguageCode.assamese)
        #expect("syr" == NSAttributedStringBuilder.LanguageCode.assyrian)
        #expect("az" == NSAttributedStringBuilder.LanguageCode.azerbaijani)
        #expect("bn" == NSAttributedStringBuilder.LanguageCode.bangla)
        #expect("be" == NSAttributedStringBuilder.LanguageCode.belarusian)
        #expect("brx" == NSAttributedStringBuilder.LanguageCode.bodo)
        #expect("bg" == NSAttributedStringBuilder.LanguageCode.bulgarian)
        #expect("my" == NSAttributedStringBuilder.LanguageCode.burmese)
        #expect("yue" == NSAttributedStringBuilder.LanguageCode.cantonese)
        #expect("ca" == NSAttributedStringBuilder.LanguageCode.catalan)
        #expect("chr" == NSAttributedStringBuilder.LanguageCode.cherokee)
        #expect("zh" == NSAttributedStringBuilder.LanguageCode.chinese)
        #expect("hr" == NSAttributedStringBuilder.LanguageCode.croatian)
        #expect("cs" == NSAttributedStringBuilder.LanguageCode.czech)
        #expect("da" == NSAttributedStringBuilder.LanguageCode.danish)
        #expect("dv" == NSAttributedStringBuilder.LanguageCode.dhivehi)
        #expect("doi" == NSAttributedStringBuilder.LanguageCode.dogri)
        #expect("nl" == NSAttributedStringBuilder.LanguageCode.dutch)
        #expect("dz" == NSAttributedStringBuilder.LanguageCode.dzongkha)
        #expect("en" == NSAttributedStringBuilder.LanguageCode.english)
        #expect("et" == NSAttributedStringBuilder.LanguageCode.estonian)
        #expect("fo" == NSAttributedStringBuilder.LanguageCode.faroese)
        #expect("fi" == NSAttributedStringBuilder.LanguageCode.finnish)
        #expect("fr" == NSAttributedStringBuilder.LanguageCode.french)
        #expect("ff" == NSAttributedStringBuilder.LanguageCode.fula)
        #expect("ka" == NSAttributedStringBuilder.LanguageCode.georgian)
        #expect("de" == NSAttributedStringBuilder.LanguageCode.german)
        #expect("el" == NSAttributedStringBuilder.LanguageCode.greek)
        #expect("gu" == NSAttributedStringBuilder.LanguageCode.gujarati)
        #expect("haw" == NSAttributedStringBuilder.LanguageCode.hawaiian)
        #expect("he" == NSAttributedStringBuilder.LanguageCode.hebrew)
        #expect("hi" == NSAttributedStringBuilder.LanguageCode.hindi)
        #expect("hu" == NSAttributedStringBuilder.LanguageCode.hungarian)
        #expect("is" == NSAttributedStringBuilder.LanguageCode.icelandic)
        #expect("ig" == NSAttributedStringBuilder.LanguageCode.igbo)
        #expect("id" == NSAttributedStringBuilder.LanguageCode.indonesian)
        #expect("ga" == NSAttributedStringBuilder.LanguageCode.irish)
        #expect("it" == NSAttributedStringBuilder.LanguageCode.italian)
        #expect("ja" == NSAttributedStringBuilder.LanguageCode.japanese)
        #expect("kn" == NSAttributedStringBuilder.LanguageCode.kannada)
        #expect("ks" == NSAttributedStringBuilder.LanguageCode.kashmiri)
        #expect("kk" == NSAttributedStringBuilder.LanguageCode.kazakh)
        #expect("km" == NSAttributedStringBuilder.LanguageCode.khmer)
        #expect("kok" == NSAttributedStringBuilder.LanguageCode.konkani)
        #expect("ko" == NSAttributedStringBuilder.LanguageCode.korean)
        #expect("ku" == NSAttributedStringBuilder.LanguageCode.kurdish)
        #expect("ckb" == NSAttributedStringBuilder.LanguageCode.kurdishSorani)
        #expect("ky" == NSAttributedStringBuilder.LanguageCode.kyrgyz)
        #expect("lo" == NSAttributedStringBuilder.LanguageCode.lao)
        #expect("lv" == NSAttributedStringBuilder.LanguageCode.latvian)
        #expect("lt" == NSAttributedStringBuilder.LanguageCode.lithuanian)
        #expect("mk" == NSAttributedStringBuilder.LanguageCode.macedonian)
        #expect("mai" == NSAttributedStringBuilder.LanguageCode.maithili)
        #expect("ms" == NSAttributedStringBuilder.LanguageCode.malay)
        #expect("ml" == NSAttributedStringBuilder.LanguageCode.malayalam)
        #expect("mt" == NSAttributedStringBuilder.LanguageCode.maltese)
        #expect("mni" == NSAttributedStringBuilder.LanguageCode.manipuri)
        #expect("mr" == NSAttributedStringBuilder.LanguageCode.marathi)
        #expect("mn" == NSAttributedStringBuilder.LanguageCode.mongolian)
        #expect("mi" == NSAttributedStringBuilder.LanguageCode.māori)
        #expect("nv" == NSAttributedStringBuilder.LanguageCode.navajo)
        #expect("ne" == NSAttributedStringBuilder.LanguageCode.nepali)
        #expect("no" == NSAttributedStringBuilder.LanguageCode.norwegian)
        #expect("nb" == NSAttributedStringBuilder.LanguageCode.norwegianBokmål)
        #expect("nn" == NSAttributedStringBuilder.LanguageCode.norwegianNynorsk)
        #expect("or" == NSAttributedStringBuilder.LanguageCode.odia)
        #expect("ps" == NSAttributedStringBuilder.LanguageCode.pashto)
        #expect("fa" == NSAttributedStringBuilder.LanguageCode.persian)
        #expect("pl" == NSAttributedStringBuilder.LanguageCode.polish)
        #expect("pt" == NSAttributedStringBuilder.LanguageCode.portuguese)
        #expect("rhg" == NSAttributedStringBuilder.LanguageCode.rohingya)
        #expect("ro" == NSAttributedStringBuilder.LanguageCode.romanian)
        #expect("ru" == NSAttributedStringBuilder.LanguageCode.russian)
        #expect("sm" == NSAttributedStringBuilder.LanguageCode.samoan)
        #expect("sa" == NSAttributedStringBuilder.LanguageCode.sanskrit)
        #expect("sat" == NSAttributedStringBuilder.LanguageCode.santali)
        #expect("sr" == NSAttributedStringBuilder.LanguageCode.serbian)
        #expect("sd" == NSAttributedStringBuilder.LanguageCode.sindhi)
        #expect("si" == NSAttributedStringBuilder.LanguageCode.sinhala)
        #expect("sk" == NSAttributedStringBuilder.LanguageCode.slovak)
        #expect("sl" == NSAttributedStringBuilder.LanguageCode.slovenian)
        #expect("es" == NSAttributedStringBuilder.LanguageCode.spanish)
        #expect("sw" == NSAttributedStringBuilder.LanguageCode.swahili)
        #expect("sv" == NSAttributedStringBuilder.LanguageCode.swedish)
        #expect("tl" == NSAttributedStringBuilder.LanguageCode.tagalog)
        #expect("tg" == NSAttributedStringBuilder.LanguageCode.tajik)
        #expect("ta" == NSAttributedStringBuilder.LanguageCode.tamil)
        #expect("te" == NSAttributedStringBuilder.LanguageCode.telugu)
        #expect("th" == NSAttributedStringBuilder.LanguageCode.thai)
        #expect("bo" == NSAttributedStringBuilder.LanguageCode.tibetan)
        #expect("to" == NSAttributedStringBuilder.LanguageCode.tongan)
        #expect("tr" == NSAttributedStringBuilder.LanguageCode.turkish)
        #expect("tk" == NSAttributedStringBuilder.LanguageCode.turkmen)
        #expect("uk" == NSAttributedStringBuilder.LanguageCode.ukrainian)
        #expect("ur" == NSAttributedStringBuilder.LanguageCode.urdu)
        #expect("ug" == NSAttributedStringBuilder.LanguageCode.uyghur)
        #expect("uz" == NSAttributedStringBuilder.LanguageCode.uzbek)
        #expect("vi" == NSAttributedStringBuilder.LanguageCode.vietnamese)
        #expect("cy" == NSAttributedStringBuilder.LanguageCode.welsh)
        #expect("yi" == NSAttributedStringBuilder.LanguageCode.yiddish)

        #expect("mul" == NSAttributedStringBuilder.LanguageCode.multiple)
        #expect("zxx" == NSAttributedStringBuilder.LanguageCode.unavailable)
        #expect("mis" == NSAttributedStringBuilder.LanguageCode.uncoded)
        #expect("und" == NSAttributedStringBuilder.LanguageCode.unidentified)

        #expect("abcdefghijklmnopqrstuvwxyz" == NSAttributedStringBuilder.LanguageCode.unknown)
    }

    @Test
    @available(macOS 13, iOS 16, tvOS 16, watchOS 9, *)
    func languageCodes() {
        #expect(NSAttributedStringBuilder.LanguageCode.ainu.rawValue == Locale.LanguageCode.ainu.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.albanian.rawValue == Locale.LanguageCode.albanian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.amharic.rawValue == Locale.LanguageCode.amharic.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.apacheWestern.rawValue == Locale.LanguageCode.apacheWestern.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.arabic.rawValue == Locale.LanguageCode.arabic.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.armenian.rawValue == Locale.LanguageCode.armenian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.assamese.rawValue == Locale.LanguageCode.assamese.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.assyrian.rawValue == Locale.LanguageCode.assyrian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.azerbaijani.rawValue == Locale.LanguageCode.azerbaijani.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.bangla.rawValue == Locale.LanguageCode.bangla.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.belarusian.rawValue == Locale.LanguageCode.belarusian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.bodo.rawValue == Locale.LanguageCode.bodo.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.bulgarian.rawValue == Locale.LanguageCode.bulgarian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.burmese.rawValue == Locale.LanguageCode.burmese.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.cantonese.rawValue == Locale.LanguageCode.cantonese.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.catalan.rawValue == Locale.LanguageCode.catalan.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.cherokee.rawValue == Locale.LanguageCode.cherokee.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.chinese.rawValue == Locale.LanguageCode.chinese.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.croatian.rawValue == Locale.LanguageCode.croatian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.czech.rawValue == Locale.LanguageCode.czech.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.danish.rawValue == Locale.LanguageCode.danish.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.dhivehi.rawValue == Locale.LanguageCode.dhivehi.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.dogri.rawValue == Locale.LanguageCode.dogri.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.dutch.rawValue == Locale.LanguageCode.dutch.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.dzongkha.rawValue == Locale.LanguageCode.dzongkha.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.english.rawValue == Locale.LanguageCode.english.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.estonian.rawValue == Locale.LanguageCode.estonian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.faroese.rawValue == Locale.LanguageCode.faroese.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.finnish.rawValue == Locale.LanguageCode.finnish.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.french.rawValue == Locale.LanguageCode.french.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.fula.rawValue == Locale.LanguageCode.fula.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.georgian.rawValue == Locale.LanguageCode.georgian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.german.rawValue == Locale.LanguageCode.german.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.greek.rawValue == Locale.LanguageCode.greek.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.gujarati.rawValue == Locale.LanguageCode.gujarati.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.hawaiian.rawValue == Locale.LanguageCode.hawaiian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.hebrew.rawValue == Locale.LanguageCode.hebrew.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.hindi.rawValue == Locale.LanguageCode.hindi.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.hungarian.rawValue == Locale.LanguageCode.hungarian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.icelandic.rawValue == Locale.LanguageCode.icelandic.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.igbo.rawValue == Locale.LanguageCode.igbo.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.indonesian.rawValue == Locale.LanguageCode.indonesian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.irish.rawValue == Locale.LanguageCode.irish.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.italian.rawValue == Locale.LanguageCode.italian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.japanese.rawValue == Locale.LanguageCode.japanese.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.kannada.rawValue == Locale.LanguageCode.kannada.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.kashmiri.rawValue == Locale.LanguageCode.kashmiri.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.kazakh.rawValue == Locale.LanguageCode.kazakh.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.khmer.rawValue == Locale.LanguageCode.khmer.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.konkani.rawValue == Locale.LanguageCode.konkani.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.korean.rawValue == Locale.LanguageCode.korean.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.kurdish.rawValue == Locale.LanguageCode.kurdish.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.kurdishSorani.rawValue == Locale.LanguageCode.kurdishSorani.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.kyrgyz.rawValue == Locale.LanguageCode.kyrgyz.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.lao.rawValue == Locale.LanguageCode.lao.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.latvian.rawValue == Locale.LanguageCode.latvian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.lithuanian.rawValue == Locale.LanguageCode.lithuanian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.macedonian.rawValue == Locale.LanguageCode.macedonian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.maithili.rawValue == Locale.LanguageCode.maithili.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.malay.rawValue == Locale.LanguageCode.malay.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.malayalam.rawValue == Locale.LanguageCode.malayalam.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.maltese.rawValue == Locale.LanguageCode.maltese.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.manipuri.rawValue == Locale.LanguageCode.manipuri.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.marathi.rawValue == Locale.LanguageCode.marathi.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.mongolian.rawValue == Locale.LanguageCode.mongolian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.māori.rawValue == Locale.LanguageCode.māori.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.navajo.rawValue == Locale.LanguageCode.navajo.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.nepali.rawValue == Locale.LanguageCode.nepali.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.norwegian.rawValue == Locale.LanguageCode.norwegian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.norwegianBokmål.rawValue == Locale.LanguageCode.norwegianBokmål.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.norwegianNynorsk.rawValue == Locale.LanguageCode.norwegianNynorsk.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.odia.rawValue == Locale.LanguageCode.odia.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.pashto.rawValue == Locale.LanguageCode.pashto.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.persian.rawValue == Locale.LanguageCode.persian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.polish.rawValue == Locale.LanguageCode.polish.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.portuguese.rawValue == Locale.LanguageCode.portuguese.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.rohingya.rawValue == Locale.LanguageCode.rohingya.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.romanian.rawValue == Locale.LanguageCode.romanian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.russian.rawValue == Locale.LanguageCode.russian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.samoan.rawValue == Locale.LanguageCode.samoan.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.sanskrit.rawValue == Locale.LanguageCode.sanskrit.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.santali.rawValue == Locale.LanguageCode.santali.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.serbian.rawValue == Locale.LanguageCode.serbian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.sindhi.rawValue == Locale.LanguageCode.sindhi.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.sinhala.rawValue == Locale.LanguageCode.sinhala.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.slovak.rawValue == Locale.LanguageCode.slovak.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.slovenian.rawValue == Locale.LanguageCode.slovenian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.spanish.rawValue == Locale.LanguageCode.spanish.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.swahili.rawValue == Locale.LanguageCode.swahili.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.swedish.rawValue == Locale.LanguageCode.swedish.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.tagalog.rawValue == Locale.LanguageCode.tagalog.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.tajik.rawValue == Locale.LanguageCode.tajik.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.tamil.rawValue == Locale.LanguageCode.tamil.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.telugu.rawValue == Locale.LanguageCode.telugu.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.thai.rawValue == Locale.LanguageCode.thai.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.tibetan.rawValue == Locale.LanguageCode.tibetan.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.tongan.rawValue == Locale.LanguageCode.tongan.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.turkish.rawValue == Locale.LanguageCode.turkish.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.turkmen.rawValue == Locale.LanguageCode.turkmen.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.ukrainian.rawValue == Locale.LanguageCode.ukrainian.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.urdu.rawValue == Locale.LanguageCode.urdu.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.uyghur.rawValue == Locale.LanguageCode.uyghur.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.uzbek.rawValue == Locale.LanguageCode.uzbek.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.vietnamese.rawValue == Locale.LanguageCode.vietnamese.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.welsh.rawValue == Locale.LanguageCode.welsh.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.yiddish.rawValue == Locale.LanguageCode.yiddish.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.multiple.rawValue == Locale.LanguageCode.multiple.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.unavailable.rawValue == Locale.LanguageCode.unavailable.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.uncoded.rawValue == Locale.LanguageCode.uncoded.identifier)
        #expect(NSAttributedStringBuilder.LanguageCode.unidentified.rawValue == Locale.LanguageCode.unidentified.identifier)
    }
}
