# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage

before_all do |lane, options|
  if is_ci
    xcode_select(ENV["XC_PATH"])
    setup_ci
  end
end

desc "Run all tests for: macOS, iOS, tvOS, watchOS & visionOS"
lane :test_all do
  env_names.each do |env|
    Dotenv.overload "#{env}"
    test
  end
end

desc "Run tests for a specific platform. Use --env to select an environment. (ios, macos, tvos, watchos or visionos)"
lane :test do |options|
  UI.important("Test #{ENV['PLATFORM_BUILD_DIRECTORY']}")
  scan(
    project: project_path,
    scheme: ENV["SCHEME"],
    clean: true,
    code_coverage: true,
    force_quit_simulator: true,
    output_directory: output_directory,
    derived_data_path: derived_data_path,
    destination: ENV["XC_SCAN_DESTINATION"],
    parallel_testing: false
  )
end

desc "Generate code coverage reports for: macOS, iOS, tvOS, watchOS & visionOS"
lane :code_coverage_all do |options|
  env_names.each do |env|
    Dotenv.overload "#{env}"
    code_coverage
  end
end

desc "Generate code coverage report for a specific platform. Use --env to select the environment. (ios, macos, tvos, watchos or visionos)"
lane :code_coverage do |options|
  UI.important("Generate coverage for #{ENV['PLATFORM_BUILD_DIRECTORY']}")
  slather(
    proj: project_path,
    scheme: ENV["SCHEME"],
    build_directory: derived_data_path,
    output_directory: coverage_output_directory,
    binary_basename: ENV["TARGET_NAME"],
    github: is_ci,
    cobertura_xml: true
  )
end

### --- Helpers --- ###

def project_path
  "NSAttributedStringBuilder.xcodeproj"
end

def derived_data_path
  File.join(ENV["FASTLANE_BUILD_DIRECTORY"], ENV["PLATFORM_BUILD_DIRECTORY"], "tests")
end

def output_directory
  File.join(ENV["FASTLANE_BUILD_DIRECTORY"], ENV["PLATFORM_BUILD_DIRECTORY"], "reports")
end

def coverage_output_directory
  File.join(ENV["FASTLANE_BUILD_DIRECTORY"], ENV["PLATFORM_BUILD_DIRECTORY"], "coverage")
end

def env_names
  [".env.ios", ".env.macos", ".env.tvos", ".env.watchos", ".env.visionos"]
end
