# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage

before_all do |lane, options|
  if is_ci
    xcode_select(ENV["XC_PATH"])
    setup_ci
  end
end

desc "Run all tests for: macOS, iOS, tvOS & watchOS"
lane :test_all do
  Dotenv.overload ".env.ios"
  test

  Dotenv.overload ".env.macos"
  test

  Dotenv.overload ".env.tvos"
  test

  Dotenv.overload ".env.watchos"
  test
end

desc "Run tests for a specific platform. Use --env to select an environment. (ios, macos, tvos or watchos)"
lane :test do |options|
  scan(
    project: project_path,
    scheme: ENV["SCHEME"],
    clean: true,
    code_coverage: true,
    force_quit_simulator: true,
    output_directory: output_directory,
    derived_data_path: derived_data_path,
    destination: ENV["XC_SCAN_DESTINATION"],
    parallel_testing: false
  )
end

### --- Helpers --- ###

def project_path
  "NSAttributedStringBuilder.xcodeproj"
end

def derived_data_path
  File.join(ENV["FASTLANE_BUILD_DIRECTORY"], ENV["PLATFORM_BUILD_DIRECTORY"], "tests")
end

def output_directory
  File.join(ENV["FASTLANE_BUILD_DIRECTORY"], ENV["PLATFORM_BUILD_DIRECTORY"], "reports")
end
