name: CI
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: bundle exec fastlane test_all

      - name: Upload code coverage reports
        uses: ./.github/actions/code-coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
